import { CustomerRecord, InvoiceRecord, LeadRecord, OrderRecord, PaymentRecord } from '../types';

// Anchor date for predictable calculation of aging & dormant intervals
export const ANCHOR_DATE = '2026-10-01';

export function getDemoInvoices(): InvoiceRecord[] {
  return [
    // CRITICAL: Overdue Invoices > 60-90 days
    {
      id: 'inv-101',
      invoiceNumber: 'INV-2026-0812',
      customerId: 'cust-01',
      customerName: 'Acme Cloud Solutions Ltd',
      date: '2026-06-15',
      dueDate: '2026-07-15', // ~77 days overdue
      amount: 145000,
      status: 'OVERDUE',
      discountPercent: 5,
      notes: 'Quarterly enterprise platform licensing. Payment reminder sent twice, finance contact went silent.',
    },
    {
      id: 'inv-102',
      invoiceNumber: 'INV-2026-0844',
      customerId: 'cust-04',
      customerName: 'Nova Dynamics Tech',
      date: '2026-07-02',
      dueDate: '2026-08-01', // ~60 days overdue
      amount: 95000,
      status: 'OVERDUE',
      discountPercent: 0,
      notes: 'Custom integration & onboarding package. Awaiting PO sign-off from VP Finance.',
    },
    {
      id: 'inv-103',
      invoiceNumber: 'INV-2026-0790',
      customerId: 'cust-07',
      customerName: 'Vertex Global Corp',
      date: '2026-05-20',
      dueDate: '2026-06-20', // ~102 days overdue
      amount: 102000,
      status: 'OVERDUE',
      discountPercent: 0,
      notes: 'Multi-seat annual expansion. Risk of write-off if not escalated to legal/executive collections.',
    },
    // HIGH: Duplicate Invoices
    {
      id: 'inv-104',
      invoiceNumber: 'INV-2026-0915',
      customerId: 'cust-09',
      customerName: 'Zenith Retail Network',
      date: '2026-08-10',
      dueDate: '2026-09-10',
      amount: 180000,
      status: 'UNPAID',
      discountPercent: 10,
      notes: 'Automated workflow sync engine batch 1.',
    },
    {
      id: 'inv-105',
      invoiceNumber: 'INV-2026-0922', // DUPLICATE of inv-104!
      customerId: 'cust-09',
      customerName: 'Zenith Retail Network',
      date: '2026-08-11',
      dueDate: '2026-09-10',
      amount: 180000,
      status: 'UNPAID',
      discountPercent: 10,
      notes: 'Automated workflow sync engine duplicate generation via ERP webhook retry bug.',
    },
    {
      id: 'inv-106',
      invoiceNumber: 'INV-2026-0931',
      customerId: 'cust-12',
      customerName: 'BlueSky Logistics',
      date: '2026-08-25',
      dueDate: '2026-09-25',
      amount: 85000,
      status: 'UNPAID',
      discountPercent: 0,
      notes: 'Fleet telemetry modules.',
    },
    {
      id: 'inv-107',
      invoiceNumber: 'INV-2026-0939', // DUPLICATE of inv-106!
      customerId: 'cust-12',
      customerName: 'BlueSky Logistics',
      date: '2026-08-25',
      dueDate: '2026-09-25',
      amount: 85000,
      status: 'UNPAID',
      discountPercent: 0,
      notes: 'Fleet telemetry modules duplicate billing from manual reissue.',
    },
    // ABNORMAL DISCOUNTS: Standard is 5-10%, these are 45% and 52% rogue discounts!
    {
      id: 'inv-108',
      invoiceNumber: 'INV-2026-0955',
      customerId: 'cust-15',
      customerName: 'Kestrel Financial Analytics',
      date: '2026-09-02',
      dueDate: '2026-10-02',
      amount: 165000,
      status: 'PAID',
      paymentDate: '2026-09-14',
      discountPercent: 48, // Rogue discount! Original value would be ~₹317,000, lost ₹152,000
      notes: 'Sales rep applied unapproved 48% executive discount voucher with no manager signature.',
    },
    {
      id: 'inv-109',
      invoiceNumber: 'INV-2026-0968',
      customerId: 'cust-18',
      customerName: 'Orbit Media House',
      date: '2026-09-10',
      dueDate: '2026-10-10',
      amount: 120000,
      status: 'PAID',
      paymentDate: '2026-09-18',
      discountPercent: 55, // Rogue discount! Original value ~₹266,000, lost ~₹146,000
      notes: 'End of month quota rush concession override without margin approval.',
    },
    // REVENUE CONCENTRATION: Single account represents giant portion
    {
      id: 'inv-110',
      invoiceNumber: 'INV-2026-0701',
      customerId: 'cust-99',
      customerName: 'Apex Systems Global Enterprise',
      date: '2026-07-01',
      dueDate: '2026-07-31',
      amount: 1250000,
      status: 'PAID',
      paymentDate: '2026-07-28',
      discountPercent: 8,
      notes: 'Enterprise annual master service agreement license.',
    },
    {
      id: 'inv-111',
      invoiceNumber: 'INV-2026-0801',
      customerId: 'cust-99',
      customerName: 'Apex Systems Global Enterprise',
      date: '2026-08-01',
      dueDate: '2026-08-31',
      amount: 850000,
      status: 'PAID',
      paymentDate: '2026-08-28',
      discountPercent: 5,
      notes: 'Custom security pipeline add-on.',
    },
    // Normal paid and current invoices
    {
      id: 'inv-112',
      invoiceNumber: 'INV-2026-0901',
      customerId: 'cust-02',
      customerName: 'Starlight E-commerce Pvt Ltd',
      date: '2026-09-01',
      dueDate: '2026-10-01',
      amount: 92000,
      status: 'PAID',
      paymentDate: '2026-09-20',
      discountPercent: 5,
    },
    {
      id: 'inv-113',
      invoiceNumber: 'INV-2026-0902',
      customerId: 'cust-03',
      customerName: 'Pulse Labs Healthcare',
      date: '2026-09-05',
      dueDate: '2026-10-05',
      amount: 140000,
      status: 'UNPAID',
      discountPercent: 0,
    },
    {
      id: 'inv-114',
      invoiceNumber: 'INV-2026-0903',
      customerId: 'cust-05',
      customerName: 'AeroTech Machining',
      date: '2026-09-08',
      dueDate: '2026-10-08',
      amount: 110000,
      status: 'UNPAID',
      discountPercent: 5,
    },
    {
      id: 'inv-115',
      invoiceNumber: 'INV-2026-0904',
      customerId: 'cust-06',
      customerName: 'Quantex Trading Systems',
      date: '2026-09-12',
      dueDate: '2026-10-12',
      amount: 220000,
      status: 'PAID',
      paymentDate: '2026-09-22',
      discountPercent: 8,
    },
    {
      id: 'inv-116',
      invoiceNumber: 'INV-2026-0905',
      customerId: 'cust-08',
      customerName: 'Horizon Real Estate Group',
      date: '2026-09-15',
      dueDate: '2026-10-15',
      amount: 75000,
      status: 'PAID',
      paymentDate: '2026-09-25',
      discountPercent: 0,
    },
    {
      id: 'inv-117',
      invoiceNumber: 'INV-2026-0906',
      customerId: 'cust-10',
      customerName: 'Catalyst BioPharma',
      date: '2026-09-18',
      dueDate: '2026-10-18',
      amount: 310000,
      status: 'PAID',
      paymentDate: '2026-09-28',
      discountPercent: 10,
    },
    {
      id: 'inv-118',
      invoiceNumber: 'INV-2026-0907',
      customerId: 'cust-11',
      customerName: 'Nexus Supply Chain',
      date: '2026-09-20',
      dueDate: '2026-10-20',
      amount: 125000,
      status: 'UNPAID',
      discountPercent: 5,
    },
    {
      id: 'inv-119',
      invoiceNumber: 'INV-2026-0908',
      customerId: 'cust-13',
      customerName: 'CyberShield Systems',
      date: '2026-09-22',
      dueDate: '2026-10-22',
      amount: 195000,
      status: 'PAID',
      paymentDate: '2026-09-29',
      discountPercent: 7,
    },
    {
      id: 'inv-120',
      invoiceNumber: 'INV-2026-0909',
      customerId: 'cust-14',
      customerName: 'Solaris Clean Energy',
      date: '2026-09-25',
      dueDate: '2026-10-25',
      amount: 155000,
      status: 'UNPAID',
      discountPercent: 0,
    },
  ];
}

export function getDemoLeads(): LeadRecord[] {
  return [
    // CRITICAL: High-Intent Leads with No Follow-up for 30+ days (totaling ₹27.5L!)
    {
      id: 'lead-201',
      leadName: 'Vikramaditya Roy',
      company: 'Titan Manufacturing Conglomerate',
      contactEmail: 'v.roy@titanmfg.in',
      dealValue: 650000,
      intentScore: 9, // Highest intent: requested bespoke quote & completed pilot
      status: 'QUALIFIED',
      createdDate: '2026-07-20',
      lastContactDate: '2026-08-14', // 48 days ago!
      assignedRep: 'Rohan Sharma',
      source: 'Inbound Enterprise Demo',
    },
    {
      id: 'lead-202',
      leadName: 'Ananya Deshmukh',
      company: 'Paramount Fintech Services',
      contactEmail: 'ananya.d@paramountfin.com',
      dealValue: 580000,
      intentScore: 10, // Pricing calculator used 3x, requested commercial contract draft
      status: 'PROPOSAL_SENT',
      createdDate: '2026-07-25',
      lastContactDate: '2026-08-18', // 44 days ago!
      assignedRep: 'Sneha Patel',
      source: 'Direct Website Demo Request',
    },
    {
      id: 'lead-203',
      leadName: 'Sanjay Malhotra',
      company: 'Apex Omni-Retail Group',
      contactEmail: 'smalhotra@apexomni.co',
      dealValue: 520000,
      intentScore: 8,
      status: 'QUALIFIED',
      createdDate: '2026-08-01',
      lastContactDate: '2026-08-22', // 40 days ago!
      assignedRep: 'Rohan Sharma',
      source: 'Webinar Attendee',
    },
    {
      id: 'lead-204',
      leadName: 'Meera Nambiar',
      company: 'Kavach Cybersecurity Systems',
      contactEmail: 'meera.n@kavachsec.io',
      dealValue: 480000,
      intentScore: 9,
      status: 'PROPOSAL_SENT',
      createdDate: '2026-08-05',
      lastContactDate: '2026-08-25', // 37 days ago!
      assignedRep: 'Sneha Patel',
      source: 'Inbound Executive Referral',
    },
    {
      id: 'lead-205',
      leadName: 'Arjun Singhania',
      company: 'NextGen Autonomous Logistics',
      contactEmail: 'arjun@nextgenauto.in',
      dealValue: 520000,
      intentScore: 9,
      status: 'QUALIFIED',
      createdDate: '2026-08-08',
      lastContactDate: '2026-08-28', // 34 days ago!
      assignedRep: 'Rohan Sharma',
      source: 'Product Hunt Enterprise Lead',
    },

    // HIGH: Dormant high-value leads (> ₹5L, untouched for > 60 days)
    {
      id: 'lead-206',
      leadName: 'Rajeshwari Iyer',
      company: 'Zenith Hospital Infrastructure',
      contactEmail: 'r.iyer@zenithmed.org',
      dealValue: 750000,
      intentScore: 6,
      status: 'CONTACTED',
      createdDate: '2026-05-15',
      lastContactDate: '2026-06-10', // 113 days ago!
      assignedRep: 'Amit Verma',
      source: 'Cold Outbound Campaign',
    },
    {
      id: 'lead-207',
      leadName: 'Gaurav Sen',
      company: 'Matrix Distributed Computing',
      contactEmail: 'gaurav@matrixcomputing.tech',
      dealValue: 620000,
      intentScore: 5,
      status: 'CONTACTED',
      createdDate: '2026-06-02',
      lastContactDate: '2026-06-28', // 95 days ago!
      assignedRep: 'Amit Verma',
      source: 'LinkedIn Sales Navigator',
    },

    // Active leads being actively worked
    {
      id: 'lead-208',
      leadName: 'Divya Kashyap',
      company: 'HyperScale Cloud Labs',
      contactEmail: 'divya@hyperscalelabs.com',
      dealValue: 420000,
      intentScore: 8,
      status: 'PROPOSAL_SENT',
      createdDate: '2026-09-15',
      lastContactDate: '2026-09-29', // Active (2 days ago)
      assignedRep: 'Sneha Patel',
      source: 'Google Ads',
    },
    {
      id: 'lead-209',
      leadName: 'Karthik Rao',
      company: 'OmniTrade Commodities',
      contactEmail: 'karthik@omnitrade.in',
      dealValue: 350000,
      intentScore: 7,
      status: 'QUALIFIED',
      createdDate: '2026-09-18',
      lastContactDate: '2026-09-28', // Active (3 days ago)
      assignedRep: 'Rohan Sharma',
      source: 'Inbound Form',
    },
    {
      id: 'lead-210',
      leadName: 'Priya Sundaram',
      company: 'Veloce Deliveries',
      contactEmail: 'priya@velocelog.in',
      dealValue: 280000,
      intentScore: 6,
      status: 'NEW',
      createdDate: '2026-09-28',
      lastContactDate: '2026-09-29', // Active (2 days ago)
      assignedRep: 'Amit Verma',
      source: 'Organic Search',
    },
  ];
}

export function getDemoCustomers(): CustomerRecord[] {
  return [
    // CRITICAL: Customers showing acute Churn Risk
    {
      id: 'cust-21',
      name: 'Optima Health Tech',
      email: 'billing@optimahealth.in',
      segment: 'Enterprise',
      totalLifetimeValue: 840000,
      orderCount: 14,
      lastOrderDate: '2026-04-12', // 172 days ago!
      previousOrderDate: '2026-03-10',
      churnRiskScore: 92,
      status: 'AT_RISK',
    },
    {
      id: 'cust-22',
      name: 'Acuity Research Group',
      email: 'finance@acuityresearch.co',
      segment: 'Mid-Market',
      totalLifetimeValue: 460000,
      orderCount: 8,
      lastOrderDate: '2026-05-02', // 152 days ago!
      previousOrderDate: '2026-04-05',
      churnRiskScore: 88,
      status: 'AT_RISK',
    },
    // HIGH: Customers with declining purchase frequency (order cadence stalled)
    {
      id: 'cust-23',
      name: 'Falcon EdTech Solutions',
      email: 'admin@falconed.in',
      segment: 'Growth',
      totalLifetimeValue: 380000,
      orderCount: 12,
      lastOrderDate: '2026-08-28',
      previousOrderDate: '2026-06-15', // Cadence went from 20 days to 74 days!
      churnRiskScore: 68,
      status: 'ACTIVE',
    },
    {
      id: 'cust-24',
      name: 'Lumina Digital Agency',
      email: 'hello@luminadigital.agency',
      segment: 'Agency',
      totalLifetimeValue: 290000,
      orderCount: 9,
      lastOrderDate: '2026-09-02',
      previousOrderDate: '2026-07-01', // Gap doubled
      churnRiskScore: 64,
      status: 'ACTIVE',
    },
    // Top Account (Revenue Concentration Risk)
    {
      id: 'cust-99',
      name: 'Apex Systems Global Enterprise',
      email: 'enterprise-procure@apexsystems.global',
      segment: 'Key Account',
      totalLifetimeValue: 2100000,
      orderCount: 2,
      lastOrderDate: '2026-08-01',
      churnRiskScore: 12,
      status: 'ACTIVE',
    },
    // Healthy Customers
    {
      id: 'cust-01',
      name: 'Acme Cloud Solutions Ltd',
      email: 'accounts@acmecloud.io',
      segment: 'Enterprise',
      totalLifetimeValue: 580000,
      orderCount: 6,
      lastOrderDate: '2026-06-15',
      churnRiskScore: 45,
      status: 'ACTIVE',
    },
    {
      id: 'cust-02',
      name: 'Starlight E-commerce Pvt Ltd',
      email: 'ops@starlightecom.in',
      segment: 'Growth',
      totalLifetimeValue: 340000,
      orderCount: 7,
      lastOrderDate: '2026-09-01',
      previousOrderDate: '2026-08-05',
      churnRiskScore: 15,
      status: 'ACTIVE',
    },
    {
      id: 'cust-06',
      name: 'Quantex Trading Systems',
      email: 'dev@quantextrading.com',
      segment: 'Enterprise',
      totalLifetimeValue: 620000,
      orderCount: 5,
      lastOrderDate: '2026-09-12',
      previousOrderDate: '2026-08-10',
      churnRiskScore: 10,
      status: 'ACTIVE',
    },
  ];
}

export function getDemoPayments(): PaymentRecord[] {
  return [
    // CRITICAL: Repeated Failed Payments (Dunning Leak)
    {
      id: 'pay-301',
      transactionId: 'TXN-90211',
      invoiceId: 'INV-SUB-01',
      customerId: 'cust-31',
      customerName: 'Trident Media Labs',
      amount: 45000,
      date: '2026-09-01',
      status: 'FAILED',
      failureReason: 'INSUFFICIENT_FUNDS',
      method: 'AUTO_DEBIT_CARD',
    },
    {
      id: 'pay-302',
      transactionId: 'TXN-90245',
      invoiceId: 'INV-SUB-01',
      customerId: 'cust-31',
      customerName: 'Trident Media Labs',
      amount: 45000,
      date: '2026-09-08',
      status: 'FAILED',
      failureReason: 'EXPIRED_CARD',
      method: 'AUTO_DEBIT_CARD',
    },
    {
      id: 'pay-303',
      transactionId: 'TXN-90289',
      invoiceId: 'INV-SUB-01',
      customerId: 'cust-31',
      customerName: 'Trident Media Labs',
      amount: 45000,
      date: '2026-09-15',
      status: 'FAILED',
      failureReason: 'CARD_DECLINED',
      method: 'AUTO_DEBIT_CARD',
    },
    // REPEATED REFUNDS on specific account/SKU
    {
      id: 'pay-304',
      transactionId: 'TXN-REF-101',
      customerId: 'cust-40',
      customerName: 'AeroDrone Dynamics',
      amount: 38000,
      date: '2026-08-10',
      status: 'REFUNDED',
      refundAmount: 38000,
      isRefund: true,
      failureReason: 'MODULE_INCOMPATIBILITY',
    },
    {
      id: 'pay-305',
      transactionId: 'TXN-REF-102',
      customerId: 'cust-40',
      customerName: 'AeroDrone Dynamics',
      amount: 38000,
      date: '2026-08-24',
      status: 'REFUNDED',
      refundAmount: 38000,
      isRefund: true,
      failureReason: 'MODULE_INCOMPATIBILITY',
    },
    {
      id: 'pay-306',
      transactionId: 'TXN-REF-103',
      customerId: 'cust-40',
      customerName: 'AeroDrone Dynamics',
      amount: 38000,
      date: '2026-09-10',
      status: 'REFUNDED',
      refundAmount: 38000,
      isRefund: true,
      failureReason: 'MODULE_INCOMPATIBILITY',
    },
    // Mismatched payment amount vs invoice (Data Inconsistency)
    {
      id: 'pay-307',
      transactionId: 'TXN-INCONSISTENT-01',
      invoiceId: 'inv-101',
      customerId: 'cust-01',
      customerName: 'Acme Cloud Solutions Ltd',
      amount: 50000, // Invoice is ₹1,45,000, partial unlinked payment of ₹50,000 left pending for 60 days
      date: '2026-07-20',
      status: 'SUCCESS',
      method: 'NEFT_WIRE',
    },
  ];
}

export function getDemoOrders(): OrderRecord[] {
  return [
    {
      id: 'ord-401',
      orderNumber: 'ORD-2026-551',
      customerId: 'cust-51',
      customerName: 'Vanguard Retail Tech',
      date: '2026-09-02',
      amount: 88000,
      status: 'CANCELLED',
      discountAmount: 0,
    },
    {
      id: 'ord-402',
      orderNumber: 'ORD-2026-552',
      customerId: 'cust-51',
      customerName: 'Vanguard Retail Tech',
      date: '2026-09-14',
      amount: 92000,
      status: 'CANCELLED',
      discountAmount: 0,
    },
    {
      id: 'ord-403',
      orderNumber: 'ORD-2026-553',
      customerId: 'cust-52',
      customerName: 'UrbanCart Logistics',
      date: '2026-09-22',
      amount: 64000,
      status: 'CANCELLED',
      discountAmount: 5000,
    },
  ];
}
